import {
  best1,
  best10,
  best11,
  best12,
  best13,
  best14,
  best15,
  best2,
  best3,
  best4,
  best5,
  best6,
  best7,
  best8,
  best9,
} from "./assets";

export const data = [
  {
    image: best1,
    title: "Body Oil & Lotion",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 3,
    category: "Perfect Concealer",
    tags: ["cosmetics", "skincare"],
    price: 39,
    producttype: "prefectconcealer",
    id: "perfect101",
  },
  {
    image: best2,
    title: "Perfect Concealer",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 2,
    category: "Perfect Concealer",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "prefectconcealer",
    id: "perfect202",
  },
  {
    image: best3,
    title: "Soft Hand Lotion",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 12,
    category: "Perfect Concealer",
    tags: ["cosmetics", "skincare"],
    price: 69,
    producttype: "prefectconcealer",
    id: "perfect303",
  },
  {
    image: best4,
    title: "Foundation Lotion",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 21,
    category: "Perfect Concealer",
    tags: ["cosmetics", "skincare"],
    price: 45,
    producttype: "prefectconcealer",
    id: "perfect404",
  },
  {
    image: best5,
    title: "Soft BB Cream",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 15,
    category: "Body Care",
    tags: ["cosmetics", "skincare"],
    price: 29,
    producttype: "bodycare",
    id: "bodycare101",
  },
  {
    image: best6,
    title: "Face Day Cream",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 12,
    category: "Body Care",
    tags: ["cosmetics", "skincare"],
    price: 69,
    producttype: "bodycare",
    id: "bodycare202",
  },
  {
    image: best7,
    title: "Face BB CReam",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 9,
    category: "Body Care",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "bodycare",
    id: "bodycare303",
  },
  {
    image: best8,
    title: "Silk Hand Cream",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 9,
    category: "Body Care",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "bodycare",
    id: "bodycare404",
  },




  {
    image: best9,
    title: "Eyelash Curler",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 9,
    category: "Mackup Equipment",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "mackupequipment",
    id: "mackupequipment101",
  },
  {
    image: best10,
    title: "Foundation",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 9,
    category: "Mackup Equipment",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "mackupequipment",
    id: "mackupequipment202",
  },
  {
    image: best11,
    title: "Blusher",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 9,
    category: "Mackup Equipment",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "mackupequipment",
    id: "mackupequipment303",
  },
  {
    image: best12,
    title: "Silk Night Cream",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 9,
    category: "Mackup Equipment",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "mackupequipment",
    id: "mackupequipment404",
  },



  {
    image: best13,
    title: "Silk Day Cream",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 5,
    category: "body care",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "awesomesoap",
    id: "awesomesoap101",
  },
  {
    image: best14,
    title: "Soft BB Cream",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 10,
    category: "body care",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "awesomesoap",
    id: "awesomesoap202",
  },
  {
    image: best15,
    title: "Silk Hand Cream",
    description: ["Viperfish scythe butterfish smelt pleco longfin escolar medusafish surfperch. Australian herring: Pacific viperfish grenadier orangestriped hatchetfish pearl danio leatherjacket. Butterflyfish crocodile shark zebra shark sergeant major peladillo ziege gunnel sea bream cavefish cobbler electric catfish medaka central mudminnow wasp fish jewel tetra","Snakehead hillstream loach salmon: black dragonfish man-of-war fish flyingfish yellow-and-black triplefin, mouthbrooder, orbicular velvetfish emperor bream sprat, wrasse thorny catfish. Gurnard leatherjacket nase tenuis flagfish zebra trout collared carpetshark, yellow-and-black triplefin ayu yellow jack"],
    instock: 8,
    category: "body care",
    tags: ["cosmetics", "skincare"],
    price: 59,
    producttype: "awesomesoap",
    id: "awesomesoap303",
  },
];


